### ISSUE TITLE
Finish Staff Verification Process

### ISSUE THREAD

**Issue by Space-Turtle0** [School-Simplified/Timmy-SchoolSimplified#109]
https://miro.com/app/board/uXjVOT602hY=/?invite_link_id=552175999307

We're waiting on the callback/webserver for the OAuth process to continue.

**Comment by AryaBuddha** [comment]
**TODO**

- [ ] Add Gsuite Taskloop on Bot
- [ ] Create webserver
- [ ] Add prod OAuth to server
- [ ] Setup SQS queue on both ends
